<?php

/* ---------------------------------------
 * Application category id
 * Date: 2005-10-14 12:11:09
 * ---
 * Database information
 *   [dataProvider] => mysql
 *   [database] => engancha-dev
 *   [host] => localhost
 *   [user] => engancha-dev
 * ---
 * DO NOT EDIT MANUALLY!!!
 * FILE GENERATED BY SCRIPT!!!
 * ---------------------------------------
 */

?>
