<?php

/* ---------------------------------------
 * Table structure
 * Table: content
 * Date: 2008-01-14 17:31:03
 * ---
 * Database information
 *   [dataProvider] => mysql
 *   [database] => webcamaleon
 *   [host] => localhost
 *   [user] => webcamaleon
 * ---
 * DO NOT EDIT MANUALLY!!!
 * FILE GENERATED BY SCRIPT!!!
 * ---------------------------------------
 */

$this->_tableName = "content";

$this->_keyField = "id_content";

$this->_cols = array (
	"id_content" => "int",
	"id_page" => "int",
	"lang" => "text",
	"meta_description" => "text",
	"meta_keywords" => "text",
	"title" => "text",
	"introtext" => "text",
	"maintext" => "text",
	"permalink" => "text",
	"date_last_update" => "date",
	"id_user_last_update" => "int"
);

$this->_labels = array (
	"id_content" => "ID de contenido",
	"id_page" => "ID de pÃ¡gina",
	"lang" => "Idioma",
	"meta_description" => html_entity_decode($label['meta_description']),
	"meta_keywords" => html_entity_decode($label['meta_keywords']),
	"title" => html_entity_decode($label['title']),
	"introtext" => html_entity_decode($label['intro_text']),
	"maintext" => html_entity_decode($label['main_text']),
	"permalink" => html_entity_decode($label['permalink']),
	"date_last_update" => "Ãltima modificaciÃ³n",
	"id_user_last_update" => "Ãltima modificaciÃ³n por"
);

$this->_isRequired = array (
	"id_content" => "1",
	"id_page" => "0",
	"lang" => "1",
	"meta_description" => "0",
	"meta_keywords" => "0",
	"title" => "1",
	"introtext" => "0",
	"maintext" => "0",
	"permalink" => "0",
	"date_last_update" => "0",
	"id_user_last_update" => "0"
);

$this->_errorMsg = array (
	"id_content" => "",
	"id_page" => "",
	"lang" => "",
	"meta_description" => "",
	"meta_keywords" => "",
	"title" => "",
	"introtext" => "",
	"maintext" => "",
	"permalink" => "",
	"date_last_update" => "",
	"id_user_last_update" => ""
);

?>
