<?php

/* ---------------------------------------
 * Table structure
 * Table: page
 * Date: 2008-01-14 16:58:58
 * ---
 * Database information
 *   [dataProvider] => mysql
 *   [database] => webcamaleon
 *   [host] => localhost
 *   [user] => webcamaleon
 * ---
 * DO NOT EDIT MANUALLY!!!
 * FILE GENERATED BY SCRIPT!!!
 * ---------------------------------------
 */

$this->_tableName = "file";

$this->_keyField = "id_file";

$this->_cols = array (
	"id_file" => "int",
	"id_content" => "int",
	"order" => "int",
	"title" => "text",
	"description" => "text",
	"filename" => "text",
	"type" => "text",
	"tag" => "text",
	"is_private" => "int"
);

$this->_labels = array (
	"id_file" => "id_file",
	"id_content" => "id_page",
	"order" => "order",
	"title" => "title",
	"description" => "description",
	"filename" => "filename",
	"type" => "type",
	"tag" => "tag",
	"is_private" => "is_private"
);

$this->_isRequired = array (
	"id_file" => "1",
	"id_content" => "1",
	"order" => "1",
	"title" => "1",
	"description" => "0",
	"filename" => "1",
	"type" => "1",
	"tag" => "0",
	"is_private" => "0"
);

$this->_errorMsg = array (
	"id_file" => "",
	"id_content" => "",
	"order" => "",
	"title" => "",
	"description" => "",
	"filename" => "",
	"type" => "",
	"tag" => "",
	"is_private" => ""
);
?>
