<?php

/* ---------------------------------------
 * Table structure
 * Table: page
 * Date: 2008-01-14 16:58:58
 * ---
 * Database information
 *   [dataProvider] => mysql
 *   [database] => webcamaleon
 *   [host] => localhost
 *   [user] => webcamaleon
 * ---
 * DO NOT EDIT MANUALLY!!!
 * FILE GENERATED BY SCRIPT!!!
 * ---------------------------------------
 */

$this->_tableName = "page";

$this->_keyField = "id_page";

$this->_cols = array (
	"id_page" => "int",
	"id_parent" => "int",
	"date_creation" => "date",
	"extra" => "text",
	"options" => "text",
	"order" => "int",
	"is_published" => "int",
	"id_user_creator" => "int"
);

$this->_labels = array (
	"id_page" => "ID pÃ¡gina",
	"id_parent" => "PÃ¡gina padre",
	"date_creation" => "Fecha de creaciÃ³n",
	"extra" => "Extra",
	"options" => "Opciones",
	"order" => $label['order'],
	"is_published" => $label['published'],
	"id_user_creator" => "Creado por"
);

$this->_isRequired = array (
	"id_page" => "1",
	"id_parent" => "1",
	"date_creation" => "1",
	"extra" => "0",
	"options" => "0",
	"order" => "1",
	"is_published" => "0",
	"id_user_creator" => "1"
);

$this->_errorMsg = array (
	"id_page" => "",
	"id_parent" => "",
	"date_creation" => "",
	"extra" => "",
	"options" => "",
	"order" => "",
	"is_published" => "",
	"id_user_creator" => ""
);
?>
