<?php

/* ---------------------------------------
 * Table structure
 * Table: page
 * Date: 2008-01-14 16:58:58
 * ---
 * Database information
 *   [dataProvider] => mysql
 *   [database] => webcamaleon
 *   [host] => localhost
 *   [user] => webcamaleon
 * ---
 * DO NOT EDIT MANUALLY!!!
 * FILE GENERATED BY SCRIPT!!!
 * ---------------------------------------
 */

$this->_tableName = "product";

$this->_keyField = "id_product";

$this->_cols = array (
	"id_product" => "int",
	"id_product_category" => "int",
	"title" => "text",
	"description" => "text",
	"order" => "int",
	"available" => "int",
	"unitary_price" => "text",
	"thumb_image" => "text",
	"big_image" => "text",
	"is_sponsor" => "int",
	"is_private" => "int",
	"lang" => "text",
	"t_nutricional" => "text",
	"envase" => "text",
	"c_envase" => "text",
	"preparacion" => "text",	
	"permalink" => "text",
	"ingredientes" => "text"
);

$this->_labels = array (
	"id_product" => "ID Product",
	"id_product_category" => "Categoría",
	"title" => "Titulo",
	"description" => "Descripción",
	"order" => "Orden",
	"available" => "Disponible",
	"unitary_price" => "Precio unitario",
	"thumb_image" => "Imagen thumbnail",
	"big_image" => "Imagen grande",
	"is_sponsor" => "Producto destacado",
	"is_private" => "Visible solo para franquiciatarios",
	"lang" => "Idioma",
	"t_nutricional" => "Tabla nutricional",
	"envase" => "Envase",
	"c_envase" => "Caracteristicas del envase",
	"preparacion" => "Como se Prepara",
	"permalink" => html_entity_decode($label['permalink']),
	"ingredientes" => "Ingredientes"
);

$this->_isRequired = array (
	"id_product" => "1",
	"id_product_category" => "1",
	"title" => "1",
	"description" => "0",
	"order" => "1",
	"available" => "0",
	"unitary_price" => "0",
	"thumb_image" => "0",
	"big_image" => "0",
	"is_sponsor" => "0",
	"is_private" => "0",
	"lang" => "1",
	"t_nutricional" => "0",
	"envase" => "0",
	"c_envase" => "0",
	"preparacion" => "0",
	"permalink" => "0",
	"ingredientes" => "0"
);

$this->_errorMsg = array (
	"id_product" => "",
	"id_product_category" => "",
	"title" => "",
	"description" => "",
	"order" => "",
	"available" => "",
	"unitary_price" => "",
	"thumb_image" => "",
	"big_image" => "",
	"is_sponsor" => "",
	"is_private" => "",
	"lang" => "",
	"t_nutricional" => "",
	"envase" => "",
	"c_envase" => "",
	"preparacion" => "",
	"permalink" => "",
	"ingredientes" => ""
);
?>