<?php
/* ---------------------------------------
 * Table structure
 * Table: page
 * Date: 2008-01-14 16:58:58
 * ---
 * Database information
 *   [dataProvider] => mysql
 *   [database] => webcamaleon
 *   [host] => localhost
 *   [user] => webcamaleon
 * ---
 * DO NOT EDIT MANUALLY!!!
 * FILE GENERATED BY SCRIPT!!!
 * ---------------------------------------
 */

$this->_tableName = "product_category";

$this->_keyField = "id_product_category";

$this->_cols = array (
	"id_product_category" => "int",
	"id_parent" => "int",
	"title" => "text",
	"description" => "text",
	"order" => "int",
	"lang" => "text",
	"permalink" => "text",
	"image" => "text"
);

$this->_labels = array (
	"id_product_category" => "ID product Category",
	"id_parent" => html_entity_decode("Categor&iacute;a padre"),
	"title" => html_entity_decode("T&iacute;tulo"),
	"description" => html_entity_decode("Descripci&oacute;n"),
	"order" => html_entity_decode("&Oacute;rden"),
	"lang" => "Idioma",
	"permalink" => html_entity_decode($label['permalink']),
	"image" => "Imagen"
);

$this->_isRequired = array (
	"id_product_category" => "1",
	"id_parent" => "0",
	"title" => "1",
	"description" => "0",
	"order" => "0",
	"lang" => "1",
	"permalink" => "0",
	"image" => "0"
);

$this->_errorMsg = array (
	"id_product_category" => "",
	"id_parent" => "",
	"title" => "",
	"description" => "",
	"order" => "",
	"lang" => "",
	"permalink" => "",
	"image" => ""
);
?>