<?php

/* ---------------------------------------
* Table structure
* Table: user_acct
* Date: 2006-04-05 18:17:45
* ---
* Database information
*   [dataProvider] => mysql
*   [database] => sdb
*   [host] => localhost
*   [user] => usrsdb
* ---
* DO NOT EDIT MANUALLY!!!
* FILE GENERATED BY SCRIPT!!!
* ---------------------------------------
*/

$this->_tableName = "user_acct";

$this->_keyField = "id_user_acct";

$this->_cols = array (
"id_user_acct" => "int",
"password" => "text",
"name" => "text",
"lastname" => "text",
"ci" => "text",
"id_type_user_acct" => "int",
"email" => "text",
"search" => "text",
"date_last_login" => "date",
"date_last_update" => "date",
"date_creation" => "date",
"active" => "int",
"genre" => "int",
"login" => "text",
"location" => "text",
"community" => "text",
"mail_format" => "text"
);

$this->_labels = array (
"id_user_acct" => "ID user account",
"login" => $label['login'],
"password" => $label['password'],
"name" => $label['names'],
"lastname" => $label['lastname'],
"ci" => "CI",
"id_type_user_acct" => $label['usertype'],
"email" => $label['email'],
"search" => "Search",
"date_last_login" => "Ultimo ingreso",
"date_last_update" => "Ultima actualizacion",
"date_creation" => "Fecha de creacin",
"active" => $label['active'],
"genre" => $label['sex'],
"location" => "Ciudad/Pa s",
"community" => "Comunidad",
"mail_format" => "Formato correo"
);

$this->_isRequired = array (
"id_user_acct" => "1",
"login" => "1",
"password" => "1",
"name" => "1",
"lastname" => "1",
"ci" => "0",
"id_type_user_acct" => "0",
"email" => "1",
"search" => "1",
"date_last_login" => "0",
"date_last_update" => "0",
"date_creation" => "1",
"active" => "1",
"genre" => "1",
"location" => "0",
"community" => "0",
"mail_format" => "0"
);

$this->_errorMsg = array (
"id_user_acct" => "",
"login" => "",
"password" => "",
"name" => "",
"lastname" => "",
"ci" => "",
"id_type_user_acct" => "",
"email" => "",
"search" => "",
"date_last_login" => "",
"date_last_update" => "",
"date_creation" => "",
"active" => "",
"genre" => ""
);

?>
