<?php

/* ---------------------------------------
 * Table structure
 * Table: user_acct_access
 * Date: 2006-04-05 17:44:19
 * ---
 * Database information
 *   [dataProvider] => mysql
 *   [database] => sdb
 *   [host] => localhost
 *   [user] => usrsdb
 * ---
 * DO NOT EDIT MANUALLY!!!
 * FILE GENERATED BY SCRIPT!!!
 * ---------------------------------------
 */

$this->_tableName = "user_acct_access";

$this->_keyField = "access";

$this->_cols = array (
	"login" => "text",
	"access" => "text"
);

$this->_labels = array (

);

$this->_isRequired = array (

);

$this->_errorMsg = array (

);

?>
